version: '3.5'

volumes:
  postgres_volume:
networks:
  nest-postgres:
    driver: bridge

services:
  db:
    build: ./db
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nest-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    networks:
      - nest-postgres

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - nest-postgres
